### ISSUE TITLE
yara. py AttributeError: 'NoneType' object has no attribute 'setComment'

### ISSUE THREAD

**Issue by ITmustang** [ghidraninja/ghidra_scripts#16]
Traceback (most recent call last):
  File "ghidra_scripts/yara.py", line 53, in <module>
    add_bookmark_comment(vaddr, current_rule)
  File "ghidra_scripts/yara.py", line 30, in add_bookmark_comment
    cu.setComment(CodeUnit.EOL_COMMENT, text)
AttributeError: 'NoneType' object has no attribute 'setComment'

**Comment by ITmustang** [comment]
solved with another issues recommendation.. https://github.com/ghidraninja/ghidra_scripts/issues/4#issuecomment-732013836
