### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by croghostrider** [ghidraninja/ghidra_scripts#4]
Hi
if I try to run the binwalk or the yara script I receive the following message in the console:
```
yara.py> Running...
CRC32_poly_Constant /root/winbin/test.exe
Failed
'NoneType' object has no attribute 'setComment'
yara.py> Finished!
```

**Comment by ettermyra** [comment]
Got the same 'NoneType' object has no attribute 'setComment' error for the binwalk extension
Running Ghidra 9.0.2

**Comment by citizenstaar** [comment]
Got the same error. Running Ghidra 9.1

**Comment by Te-k** [comment]
Same here with Ghidra 9.1.2.

The error come from a bad conversion from physical address to logical address : yara returns a physical address in the binary, while you need the logical address to add bookmark and comment. The conversion here `addr = currentProgram.minAddress.add(addr_int)` does not work

**Comment by Te-k** [comment]
I have opened a ticket to check with Ghidra devs if there is a way to do that https://github.com/NationalSecurityAgency/ghidra/issues/2067

**Comment by CarlOlson** [comment]
Same issue on Ghidra 9.2

```
yara.py> Running...
Found : Big_Numbers0 - 0xdadb97 - 0x140db0197L
Traceback (most recent call last):
  File "/home/carl/git/ghidra_scripts/yara.py", line 53, in <module>
    add_bookmark_comment(vaddr, current_rule)
  File "/home/carl/git/ghidra_scripts/yara.py", line 30, in add_bookmark_comment
    cu.setComment(CodeUnit.EOL_COMMENT, text)
AttributeError: 'NoneType' object has no attribute 'setComment'
yara.py> Finished!
```

It works if I change `yara.py:30` to this:
```python
currentProgram.getListing().setComment(gaddr, CodeUnit.EOL_COMMENT, text)
```
